chatPrefix: "&6[PixelCore]"
serverName: "&aPixel&cWar"
ScoreboardRefreshDelay: 5
filterFromPrefixForScoreboard: "|"
discordLink: "https://discord.gg/Fce224eSzf"
cacheTimeout: 30

database:
  host: localhost
  port: 3306
  database: ServerCore
  user: admin
  password: JDuJm39dt82X5U4g