name: ServerCore
version: '${project.version}'
main: Kyu.ServerCore.Main
api-version: 1.18
depend: [LuckPerms, BetterEconomy, Vault]

commands:
  gamemode:
    aliases:
      - gm
    description: Allows the user to change their gamemode
  teleport:
    aliases:
      - tp
    description: Allows the user to teleport himself or other players
  discord:
    aliases:
      - dc
    description: Shows the discord link
  sReload:
    description: Reloads the plugin
  ping:
    description: shows your ping in ms
  invsee:
    descriptions: lets you see the inventory of another player and interact with it
  vanish:
    description: hides you from other players

permissions:
  core.reload:
    default: false
    description: Alows the usage of the reload command
  core.gamemode:
    description: Allows the usage of the gamemode command
    default: false
  core.gamemode.others:
    description: Allows setting the gamemode of others, gives the gamemode permission as well
    default: false
    children: [core.gamemode]
  core.teleport:
    description: Allows the usage of the teleport command
    default: false
  core.teleport.others:
    description: Allows teleporting other player, gives the teleport permission as well
    default: false
    children: [core.teleport]
  core.essentials.vanish:
    description: Allows the usage of the vanish command
    default: false
  core.essentials.invsee:
    description: Allows the usage of the invsee command
    default: false
  core.essentials.ping:
    descriptions: Allows the usageo of the ping command
    default: false
  core.essentials.*:
    description: Allows all essentials commands
    default: false
    children: [core.essentials.vanish, core.essentials.invsee, core.essentials.ping]
  core.colorchat:
    description: Allows the user of color codes in chat
    default: false
  core.ignoreLuckDenial:
    description: Users with this permission bypass the LuckPerms Weight Check
    default: false
  core.mod:
    description: Access to all moderation related commands
    default: false
  core.*:
    description: Full access
    default: false
    children:
      - core.gamemode.others
      - core.teleport.others
      - core.colorchat
      - core.mod
      - core.reload
      - core.essentials.*
