chatPrefix: "&6[PixEssentials]"

tpaTimeout: 30
enableHomeModule: true
enableInfoCommandModule: true
enableSpawnModule: true
enableTpaModule: true

database:
  host: localhost # host of your database
  port: 3306 # default port for MySQL
  database: db # name of your database. A database server can contain multiple databases
  user: username
  password: passy