name: pixessentials
version: 1.0-SNAPSHOT
author: Kyu
main: kyu.pixesssentials.Main
api-version: 1.18
softdepend: [Multiverse-Core]


commands:
  setSpawn:
    description: sets the Spawn
  spawn:
    description: teleports to the spawn
  cb:
    description: gives a description of the CityBuild mode and all important mechanics/commands
  eReload:
    description: reloads the plugin configs
  sethome:
    description: set a home at your location
  home:
    description: teleport to your home
  tpa:
    description: send a tp request to someone
  tpaccept:
    description: accept the most recent tp request
  tps:
    description: shows the tps of the servers
  enchant:
    description: enchant your currently held item
  smite:
    description: summon lightning at someones location
  setWarp:
    description: Sets a warp
  warp:
    description: Warps to a warp
  delWarp:
    description: Deletes a warp
  listWarps:
    description: Lists all warps