chatPrefix: "&6[Cities]"

ConfirmTimeout: 10 # How many seconds a user has to confirm a dangerous command

database:
  host: localhost # host of your database
  port: 3306 # default port for MySQL
  database: db # name of your database. A database server can contain multiple databases
  user: username
  password: passy

CityCost: 100000
CityStartChunks: 1 # How many chunks a city has right after founding
CityLevelsPerChunk: 2 # How many City Levelups you need for a new chunk
CityEXPCurveType: exponential #Linear or Exponential
CityEXPCurveLinear:
  ExpPerLevel: 1500
CityEXPCurveExponential:
 #Calculates the following: Base ^ (exp + (multiplier * level))
  Base: 100
  exp: 1.01
  multiplier: 0.1

JobLevelCurveType: linear
JobEXPCurveLinear:
  ExpPerLevel: 1000
JobEXPCurveExponential:
 #Calculates the following: Base ^ (exp + (multiplier * level)) = exp;
  Base: 100
  exp: 1.01
  multiplier: 0.1

# How many Jobs a player can have at maximum
MaxJobs: 1
# Cost of quitting one of your Jobs
JobSwapCost: 10000

# What percentage of the Job EXP is converted to City EXP
# Can be overridden individually 
JobToCityEXPConversion: 25
# Can be: 
# NONE (no rounding)
# UP (always up)
# DOWN (always down)
# HALF (round up at .5)
JobToCityEXPConversionRounding: NONE
# Whether bred Animals should award JobEXP when in EXP Table
AllowBredAnimalsForEXP: false
# Whether Mobs spawned by a spawn should award JobEXP when in EXP Table
AllowSpawnerMobsForEXP: false

Jobs:
  Miner:
    BlocksExp:
      Stone:
        Job: 1
        City: 0
      Coal_ore:
        Job: 5
      Iron_ore:
        Job: 20
      Gold_ore:
        Job: 30
      Diamond_ore:
        Job: 50
      Emerald_ore:
        Job: 100
  Hunter:
    EntitiesExp:
      Sheep:
        Job: 50
      Pig:
        Job: 50
      Rabbit:
        Job: 100
      Ender_dragon:
        Job: 1000
      Dolphin:
        Job: 500
      